### ISSUE TITLE
Where is utils module?

### ISSUE THREAD

**Issue by YantianZha** [gdesjardins/ssrbm#1]
Hi, I'm using your code by first running the ssrbm.py. I'm confused with the line "from utils import tools" that I can't find utils in your package. I also don't know where should I download it.

Also, can you give me a link of downloading pylearn? I only found out where to download pylearn2

Thanks a lot!

**Comment by gdesjardins** [comment]
Sorry for taking so long to resolve the issue (needed to resurrect some old credentials to track down the missing files).

I've commited the "utils" package as is under "ssrbm/utils". You may need to play a bit with the package structure to get things running, but at least all the code should be there. Let me know if you run into any additional problem.
